### ISSUE TITLE
Infinite loading inside vertical-stack-in-card

### ISSUE THREAD

**Issue by murmelbahn** [TheLastProject/lovelace-valetudo-map-card#10] opened 2019-09-14 06:01 UTC
Hi,

at first I have to thank you for your amazin work.
I'm using the card since it poped up in my hacs. After I configured everything it works fine but since I updatet the card yesterday I didn't see the map anymore only the spinner:/ I've tested different browser and the IOS app.

I've checked the documentation for changes since the last version but did not find anything.

Can you give me a hint for debugging this error?

**Comment by TheLastProject** [comment] 2019-09-14 06:05
Well, first things first, could you open your browser's development console and see if there are any JavaScript errors logged?

**Comment by murmelbahn** [comment] 2019-09-14 07:11
Thank you for your quick response!

Here are the errors I get from Firefox:

> 

Source-Map-Fehler: TypeError: Invalid URL: scripts.js.map
Ressourcen-Adresse: data:text/javascript;charset=utf-8,%2F*!%20For%20license%20information%20please%20see%20scripts.js.LICENSE%20*%2F%0A!function(t)%7Bvar%20e%3D%7B%7D%3Bfunction%20s(i)%7Bif(e%5Bi%5D)return%20e%5Bi%5D.exports%3Bvar%20n%3De%5Bi%5D%3D%7Bi%3Ai%2Cl%3A!1%2Cexports%3A%7B%7D%7D%3Breturn%20t%5Bi%5D.call(n.exports%2Cn%2Cn.exports%2Cs)%2Cn.l%3D!0%2Cn.exports%7Ds.m%3Dt%2Cs.c%3De%2Cs.d%3Dfunction(t%2Ce%2Ci)%7Bs.o(t%2Ce)%7C%7CObject.defineProperty(t%2Ce%2C%7Bconfigurable%3A!1%2Cenumerable%3A!0%2Cget%3Ai%7D)%7D%2Cs.r%3Dfunction(t)%7BObject.defineProperty(t%2C%22__esModule%22%2C%7Bvalue%3A!0%7D)%7D%2Cs.n%3Dfunction(t)%7Bvar%20e%3Dt%26%26t.__esModule%3Ffunction()%7Breturn%20t.default%7D%3Afunction()%7Breturn%20t%7D%3Breturn%20s.d(e%2C%22a%22%2Ce)%2Ce%7D%2Cs.o%3Dfunction(t%2Ce)%7Breturn%20Object.prototype.hasOwnProperty.call(t%2Ce)%7D%2Cs.p%3D%22%22%2Cs(s.s%3D0)%7D(%5Bfunction(t%2Ce%2Cs)%7B%22use%20strict%22%3Bfunction%20i(t%2Ce…

Source-Map-Fehler: TypeError: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: moz-extension://1057d117-e4ad-4a9b-8b84-5cb58072199d/0.js
Source-Map-Adresse: 0.js.map

Source-Map-Fehler: TypeError: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: moz-extension://1057d117-e4ad-4a9b-8b84-5cb58072199d/1.js
Source-Map-Adresse: 1.js.map

Source-Map-Fehler: TypeError: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: moz-extension://1057d117-e4ad-4a9b-8b84-5cb58072199d/inject.js
Source-Map-Adresse: inject.js.map

I don't know if this are errors from the card.

**Comment by TheLastProject** [comment] 2019-09-14 09:07
Nah, source maps just help debug minimized Javascript code, but I haven't minimized the code in this card anyway. So sadly, none of the errors are relevant. Are you sure it never loads and doesn't just take very long? The loading thing is just a hack to hide #4 that I need to remove once I find a proper solution (#5).

**Comment by TheLastProject** [comment] 2019-09-24 19:37
I'm going to close this issue as I sadly cannot reproduce it myself. Feel free to reopen this with some more info if it's still an issue for you so I can see if I can maybe reproduce the issue then

**Comment by Skeletorjus** [comment] 2019-10-16 19:58
I experienced the same bug when having the map in a [vertical-stack-in-card](https://github.com/custom-cards/vertical-stack-in-card). After taking the map out of the custom card everything laoded fine.

**Comment by TheLastProject** [comment] 2019-10-16 21:04
Thank you for that info, I'll try to see if I can reproduce it with that info soon. @murmelbahn, were you also using vertical-stack-in-card?

**Comment by murmelbahn** [comment] 2019-10-17 09:06
Yes I'm also using the map in a vertical-stack. I will give it a try at the weekend and will report if the error is gone when I'm using it without.

**Comment by jstehlik** [comment] 2019-10-27 13:15
Hey, I'm not so versed with JS but I've managed to debug it and fix it for myself. While at first the map renders black, as soon as it's redrawn (such as moving vacuum) it works all fine, so it's okay for me for now.

I've found out, that the parentElement, which I'm assuming should be the vertical-stack-in-card, was null. But the parentNode.host path leads to vertical-stack-in-card aswell, so that works.

And since parentElement is null, colors can't be resolved as well. But that can be fixed by omitting parentElement completely.

Here's the two parts I've fixed, so I hope it can be of any help towards solving this.
At: https://github.com/TheLastProject/lovelace-valetudo-map-card/blob/master/valetudo-map-card.js#L293
Changing `if (!this.parentElement) {` to `if (!this.parentNode.host) {`

And then: https://github.com/TheLastProject/lovelace-valetudo-map-card/blob/master/valetudo-map-card.js#L316-L323
Each line removing **parentElement**, so from `this.calculateColor(this.parentElement,` to just `this.calculateColor(this,`

**Comment by TheLastProject** [comment] 2019-10-27 14:29
Hmm, so it is directly related to #4 and the #5 workaround. I wish we could just find a way to grab the CSS color variables like `--accent-color` instantly somehow...

**Comment by TheLastProject** [comment] 2019-10-27 14:47
You gave me an idea though... could you try the latest commit?

**Comment by jstehlik** [comment] 2019-10-27 14:54
Yeah, seems that it helped :) Tried it on my computer and phone and it's all fine - no spinner and colors load up immediately.

**Comment by TheLastProject** [comment] 2019-10-27 15:02
Okay, closing this with fixed in 51c74656e3078333767db7fd26f0ca3f25db6f6b then :)

**Closed by TheLastProject** 2019-10-27 15:02 UTC
