### ISSUE TITLE
Add the possibility to display no go areas and virtual walls

### ISSUE THREAD

**Issue by rmickael62** [TheLastProject/lovelace-valetudo-map-card#18] opened 2019-10-23 18:54 UTC
mqtt log :
,"charger":[25665,25963],"robot":[25631,25759],"no_go_areas":[[27838,23582,30358,23582,30358,26081,27838,26081]],"virtual_walls":[[29950,23250,30000,26200]]}
Thank you

**Comment by TheLastProject** [comment] 2019-10-23 19:04
Sounds like a good idea. Could you add a screenshot of how that part of the output (charger, robot, no-go, virtual wall) looks in your Valetudo GUI so I could reference it while coding this make sure I don't accidentally confuse X and Y values or something? Especially the no-go area seems a bit weird because it has 8 values.

**Comment by rmickael62** [comment] 2019-10-23 19:25
thank you for interest in my idea and sorry I'm french and very awkward
with languages I hope this can satisfy you for your coding :
"robot":[25631,25759],"no_go_areas":[[27838,23582,30358,23582,30358,26081,27838,26081]],"virtual_walls":[[29950,23250,30000,26200]]}
[image: exemple.jpg]
Do not hesitate to ask me for other info

Le mer. 23 oct. 2019 à 21:04, Sylvia van Os <notifications@github.com> a
écrit :

**Comment by TheLastProject** [comment] 2019-10-23 19:34
The image sadly isn't visible for me :(

**Comment by rmickael62** [comment] 2019-10-23 19:36
Le mer. 23 oct. 2019 à 21:34, Sylvia van Os <notifications@github.com> a
écrit :

**Comment by rmickael62** [comment] 2019-10-23 19:39
https://drive.google.com/open?id=0Bzqk6mQwTzLGVWdJSnI4cEpHWFU4V3ZWMy1CRWdaZEdrOVFz


Le mer. 23 oct. 2019 à 21:36, Mickael RUCKEBUSCH <rmickael62@gmail.com> a
écrit :

**Comment by TheLastProject** [comment] 2019-10-23 19:46
That is super helpful, thanks!

![exemple](https://user-images.githubusercontent.com/1885159/67428505-88500080-f5de-11e9-8fef-155dc18f85e3.jpg)

**Comment by TheLastProject** [comment] 2019-10-23 20:31
I added virtual walls in 4b560e817b301669314d5d086324025cc7fff37d. I'll try to add no-go areas tomorrow. Do you know if they can be rotated? I can't create any no-go areas myself because of a bug.

**Comment by rmickael62** [comment] 2019-10-23 20:47
Only the vitual-walls can be rotated but not the areas
the result is good, it lacks only a little thickness
![wall](https://user-images.githubusercontent.com/34349993/67432702-044e4680-f5e7-11e9-91f6-87e9739d93dc.jpg)
thank you

**Comment by TheLastProject** [comment] 2019-10-24 18:56
I quite like the virtual wall being so thin myself, but I've added a virtual_wall_width variable which you can set to change the thickness of the wall :)

The no go areas are a bit harder to do then I expected (because they can be any shape, not just squares) so that'll take me somewhat longer (unless someone comes along to help).

**Comment by TheLastProject** [comment] 2019-10-25 17:04
Fixed in 4a32836ef5afd75a62497d7815c9035ff43ec207.

**Closed by TheLastProject** 2019-10-25 17:04 UTC
Labels: enhancement

**Comment by rmickael62** [comment] 2019-10-25 17:34
Apparently it works if I erase the virtual_wall and the no_go_area then if I start by building the no_go_area first.

On the other hand it is possible to display the no_go_area with transparency?

**Comment by TheLastProject** [comment] 2019-10-25 17:48
Please try an rgba value like "rgba(255, 0, 0, 0.2)" as no_go_area_color.

**Comment by rmickael62** [comment] 2019-10-25 17:51
Thanks it works

**Comment by rmickael62** [comment] 2019-10-25 19:22
Two or three lines form around the no_go_area and vary with the virtual_wall_width parameter :
this is normal?

![no go area 2](https://user-images.githubusercontent.com/34349993/67598120-0e9a4d00-f76d-11e9-8741-0c2a4c3e4e66.png)
![no go area 1](https://user-images.githubusercontent.com/34349993/67598121-0e9a4d00-f76d-11e9-9ffd-ed992f53921d.png)

**Comment by TheLastProject** [comment] 2019-10-25 19:26
No and I don't really understand why that would happen

**Comment by TheLastProject** [comment] 2019-10-26 12:24
I can reproduce it but I really have no clue what would be causing this, please make a new issue so I can tag it with "help wanted".
