### ISSUE TITLE
Add hints to custom buttons ?

### ISSUE THREAD

**Issue by jds11111** [TheLastProject/lovelace-valetudo-map-card#65] opened 2020-08-04 22:27 UTC
The custom buttons are great (once I figured out how to implement them).  I had to pick icons for them, which could sometimes be a little opaque, especially for a housemate.  It would be very useful to add hint bubbles when you hover over the icons.  These could default to something like the command, but be changeable.

**Comment by TheLastProject** [comment] 2020-08-05 06:53
Hovering isn't possible on mobile though normally. How about being able to just add text next to the icon? I think that would solve your issue too?

**Comment by jds11111** [comment] 2020-08-05 10:53
I thought about that, too. The problem with words is the amount of space they take up. Right now I have a very nice looking, uniform row of icon buttons that I can quickly scan. 

Ideally, it would be nice to place the buttons or icons on the correct part of the map, so that I could just glance at that part of the house and know what to do. But I suspect that is nontrivial to accomplish on a dynamic map. The information about zone location and size is in valetudo. Maybe it could be used to place a duplicate of the icon in the upper left corner, for example.

The hovering bit is usually something that I use a few times until I learn the buttons. A long press on mobile sometimes accomplishes the same thing as hovering, no?  This would probably be easier.

**Comment by TheLastProject** [comment] 2020-08-15 11:24
Well, the issue is that long-pressing a button actually already means something in the Home Assistant world, which makes it inconsistent to use long-press for something different.

**Comment by ottelo9** [comment] 2020-12-29 16:18
Is there a chance to add a names to my custom buttons?

**Comment by TheLastProject** [comment] 2020-12-29 20:32
Fixed in 22e44b9353e65abc32a508f9901c558808e6e1c3 as text next to the button.

**Closed by TheLastProject** 2020-12-29 20:32 UTC
Labels: enhancement
